platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: latest

outputs:
- name: test-out

run:
  path: sh
  args:
    - -exc
    - |
       cat /dev/urandom | tr -dc 'a-z' | head -c 6 > test-out/generated
       cat test-out/generated
