resources:
- name: smuggler-test
  type: git
  source:
    uri: https://github.com/tobias-johansson/smuggler-test
    branch: master

jobs:
- name: generate
  plan:
  - get: smuggler-test
    trigger: true
  - task: gen
    file: smuggler-test/ci/build.yml
